### ISSUE TITLE
Job failing with very little error output

### ISSUE THREAD

**Issue by kabudu** [danhunsaker/php-resque#3]
Following on from the discussion [here](https://github.com/chrisboulton/php-resque/issues/274), I'm attempting to use your version of the library, tag ```v1.3.2```, but all my jobs are failing with the following error stored in Redis:

```
"exception": "Resque_Job_DirtyExitException",
"error": "Job exited with exit code 255",
"backtrace": [
    "#0 \/var\/www\/html\/vendor\/danhunsaker\/php-resque\/bin\/resque(185): Resque_Worker->work(5, false)",
    "#1 {main}"
  ],
```

The above doesn't really tell me what the problem is. I was wondering if this is an issue you've come across before and have some ideas as to what could be wrong. I'm using the latest version of redis available [here](https://hub.docker.com/_/redis/)

I haven't come across this issue using the ```master ``` branch of chrisboulton's version of the library.

**Comment by kabudu** [comment]
I managed to solve my problem by switching to this version of the redis container image: ```redis:3.2.6-alpine``` and redirecting the output of ```vendor/bin/resque``` to a file.

**Comment by danhunsaker** [comment]
Sorry I didn't respond sooner.  Exit code 255 is a PHP Fatal Error, which means we get exactly as much detail as PHP provides for *any* of its fatal errors, but not necessarily anywhere useful.  You'll pretty much need to collect the worker's STDOUT to get more detail on why it was dying with the prior Redis version.
